package com.itss.projectmanagement.enums;

public enum NotificationType {
    TASK_ASSIGNED,
    TASK_UPDATED,
    TASK_COMPLETED,
    PEER_REVIEW_ASSIGNED,
    PEER_REVIEW_COMPLETED,
    PEER_REVIEW_REQUIRED,
    PEER_REVIEW_REMINDER,
    GROUP_INVITATION,
    PROJECT_INVITATION,
    PROJECT_NOTIFICATION,
    FREE_RIDER_ALERT,
    PRESSURE_SCORE_WARNING,
    GENERAL,
    SYSTEM_NOTIFICATION
} 